//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMatrix", ReplyAction="http://tempuri.org/IService1/GetMatrixResponse")]
        string GetMatrix(string matrix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMatrix", ReplyAction="http://tempuri.org/IService1/GetMatrixResponse")]
        System.Threading.Tasks.Task<string> GetMatrixAsync(string matrix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MultiplyMatrix", ReplyAction="http://tempuri.org/IService1/MultiplyMatrixResponse")]
        string MultiplyMatrix(string matrixA, string matrixB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MultiplyMatrix", ReplyAction="http://tempuri.org/IService1/MultiplyMatrixResponse")]
        System.Threading.Tasks.Task<string> MultiplyMatrixAsync(string matrixA, string matrixB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendMatrix", ReplyAction="http://tempuri.org/IService1/SendMatrixResponse")]
        string SendMatrix(string matrix, int row, int col);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendMatrix", ReplyAction="http://tempuri.org/IService1/SendMatrixResponse")]
        System.Threading.Tasks.Task<string> SendMatrixAsync(string matrix, int row, int col);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference1.IService1>, ConsoleApp1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMatrix(string matrix) {
            return base.Channel.GetMatrix(matrix);
        }
        
        public System.Threading.Tasks.Task<string> GetMatrixAsync(string matrix) {
            return base.Channel.GetMatrixAsync(matrix);
        }
        
        public string MultiplyMatrix(string matrixA, string matrixB) {
            return base.Channel.MultiplyMatrix(matrixA, matrixB);
        }
        
        public System.Threading.Tasks.Task<string> MultiplyMatrixAsync(string matrixA, string matrixB) {
            return base.Channel.MultiplyMatrixAsync(matrixA, matrixB);
        }
        
        public string SendMatrix(string matrix, int row, int col) {
            return base.Channel.SendMatrix(matrix, row, col);
        }
        
        public System.Threading.Tasks.Task<string> SendMatrixAsync(string matrix, int row, int col) {
            return base.Channel.SendMatrixAsync(matrix, row, col);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GenerateMandelbrottSet", ReplyAction="http://tempuri.org/IService2/GenerateMandelbrottSetResponse")]
        string GenerateMandelbrottSet(int x, int y, int threadsAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GenerateMandelbrottSet", ReplyAction="http://tempuri.org/IService2/GenerateMandelbrottSetResponse")]
        System.Threading.Tasks.Task<string> GenerateMandelbrottSetAsync(int x, int y, int threadsAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GetMandelbrottSet", ReplyAction="http://tempuri.org/IService2/GetMandelbrottSetResponse")]
        string GetMandelbrottSet(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GetMandelbrottSet", ReplyAction="http://tempuri.org/IService2/GetMandelbrottSetResponse")]
        System.Threading.Tasks.Task<string> GetMandelbrottSetAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : ConsoleApp1.ServiceReference1.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference1.IService2>, ConsoleApp1.ServiceReference1.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GenerateMandelbrottSet(int x, int y, int threadsAmount) {
            return base.Channel.GenerateMandelbrottSet(x, y, threadsAmount);
        }
        
        public System.Threading.Tasks.Task<string> GenerateMandelbrottSetAsync(int x, int y, int threadsAmount) {
            return base.Channel.GenerateMandelbrottSetAsync(x, y, threadsAmount);
        }
        
        public string GetMandelbrottSet(string name) {
            return base.Channel.GetMandelbrottSet(name);
        }
        
        public System.Threading.Tasks.Task<string> GetMandelbrottSetAsync(string name) {
            return base.Channel.GetMandelbrottSetAsync(name);
        }
    }
}
